### ISSUE TITLE
build:zips task runs out of memory on server with 16G RAM

### ISSUE THREAD

**Issue by markbreedlove** [mitodl/hugo-course-publisher#195]
When I run `npm run build:zips` on an AWS t3a.xlarge instance with 16G RAM and no other apps using significant memory, the process is killed with an out of memory error. So far I have tried this twice.

**Comment by gumaerc** [comment]
I hadn't tested it yet with the full course load actually, so that's good to know.  It can be skipped for now until I can figure out how to make it work.

**Comment by gumaerc** [comment]
Actually, now that I think about it, I did test that but I have 32GB of RAM on this machine.

**Comment by pdpinch** [comment]
@gumaerc @blarghmatey has this been resolved?

**Comment by gumaerc** [comment]
It has not.  Currently I am working on setting up a way for static content (images, PDF's) to be included in the site build in a way that it can be used either in the hosted site or offline.  I figured I would hold off on fixing the single course zip building process until that is in place so that these zips are fully usable offline, as intended.
