### ISSUE TITLE
New courses section on home page

### ISSUE THREAD

**Issue by pdpinch** [mitodl/hugo-course-publisher#240]
As a user, I'd like to see a display of new courses on the home page. 

#### Designs and Mockups

- wireframes at https://projects.invisionapp.com/d/main?origin=v7#/console/18609637/426576569/comments?scrollOffset=2599
- ~~card fields are not yet final~~

#### Acceptance Criteria:

- [ ] discuss the approach for fetching the necessary data and when the page gets built

**Comment by noisecapella** [comment]
It looks like we should use the same course search API we are using for the course search. We should add a [sort](https://www.elastic.co/guide/en/elasticsearch/reference/6.8/search-request-sort.html) to the query on the `created_at` field , and a size of 4 since there are four cards on the home page.

For the UI, it looks like all the information is already displayed in the search page so we can probably just copy and modify `LearningResourceDisplay`
