### ISSUE TITLE
site speed things

### ISSUE THREAD

**Issue by alicewriteswrongs** [mitodl/hugo-course-publisher#317]
We should look into various enhancements and changes we can make to keep the site speedy.

some initial ideas:

- add google pagespeed insights to our build process
- split up JS bundles to not load everything on every page
- look into using react server-side rendering to render the homepage search react component as a partial that can be included in the hugo build
- eliminate jquery and replace with plain JS (#316)

any other ideas? @noisecapella @gumaerc

**Comment by noisecapella** [comment]
Have we used the webpack bundle analyzer to see what can be cut out? The JS bundle seems a bit large at 989k

**Comment by aliceriot** [comment]
jquery is an early candidate there...and there's a few things

btw I have the bundle analyzer added to the project, you can do

```
npm run webpack:stats
npm run webpack:analyze
```

to run it locally

**Comment by aliceriot** [comment]
the library we're using for the "coming soon!" popups was also taking up some significant space iirc, although obviously that will be removed as we move out of beta. The 'bodybuilder' package used for constructing elasticsearch queries also unfortunately depends on the whole lodash package instead of using the separate, per-function modules, so the bundle currently includes the whole lodash package. Splitting up bundles into functional units (course page, home page, PDF viewer, video gallery, search page) will help with that on most pages though.
