### ISSUE TITLE
fmt issue if you run npm run build outside docker

### ISSUE THREAD

**Issue by gumaerc** [mitodl/hugo-course-publisher#70]
### Steps to Reproduce

1. run `yarn install && npm run build` directly within the source directory to build the project locally, outside of docker
2. run `npm run fmt`

### Expected Behavior

fmt should ignore the `dist` folder created by the build under `src` or it shouldn't be created there in the first place

### Actual Behavior

fmt tries to beautify the transpiled css and js under `src/dist` and takes a very long time, eventually telling you that it processed 1 file, when it actually didn't, causing `npm run fmt:check` to perpetually fail until the `src/dist` folder is removed.

**Comment by aliceriot** [comment]
I think though that you may have just had `src/dist` hanging around as an artifact - the current build setup puts everything in a top-level `dist` folder so the formatter shouldn't see it at all.

I think after this PR: https://github.com/mitodl/hugo-course-publisher/pull/65 (the one to fix the build error we had because of an improper build path for the CSS / JS) the issue should be fixed going forward.

to test I deleted `dist` and ran a local build, the formatter didn't hang afterwards and all build artifacts were in the top level directory.

**Comment by gumaerc** [comment]
I tried this again, and you're correct.  It seems it was just hanging around in my project as an artifact.  Closing.
